#!/bin/sh

case "$1" in
    start)
       echo "Loading ldd kernel modules"
       cd /usr/bin/
       scull_load
       module_load faulty
       insmod hello.ko
       aesdchar_load
       ;;
    stop)
       echo "Unloading ldd kernel modules"
       cd /usr/bin/
       scull_unload
       module_unload faulty
       rmmod hello
       aesdchar_unload
       ;;
    *)
       echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0