#!/bin/sh

case "$1" in
    start)
       echo "Loading ldd kernel modules"
       /usr/bin/ldd/scull_load
       /usr/bin/ldd/misc_load faulty
       insmod /usr/bin/ldd/hello.ko
       ;;
    stop)
       echo "Unloading ldd kernel modules"
       /usr/bin/ldd/scull_unload
       /usr/bin/ldd/misc_unload faulty
       rmmod hello
       ;;
    *)
       echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0